
CREATE PROC THEM_DANH_MUC_SP @TEN_LOAI NVARCHAR(50)
AS
	DECLARE @ID_LOAI INT
	SET @ID_LOAI = (SELECT MAX(ID_LOAI)+1
					FROM DANH_MUC_SP)
	insert into DANH_MUC_SP
	VALUES(@ID_LOAI, @TEN_LOAI)
GO

 
CREATE PROC SUA_DANH_MUC_SP @ID_LOAI INT, @TEN_LOAI NVARCHAR(50)
AS
	UPDATE DANH_MUC_SP
	SET TEN_LOAI = @TEN_LOAI
	WHERE ID_LOAI=@ID_LOAI
GO

CREATE PROC XOA_DANH_MUC_SP @ID_LOAI INT
AS
	DELETE DANH_MUC_SP
	WHERE ID_LOAI=@ID_LOAI
GO
 
CREATE PROC XEM_CHI_TIET_CHI_NHANH @ID_CN INT
AS
	SELECT TEN_CN, DIA_CHI_CN 
	FROM CHI_NHANH
	WHERE ID_CN=@ID_CN
GO

CREATE PROC XEM_SAN_PHAM_CON @ID_CN INT
AS
	SELECT sp.TEN_SP, spcn.SO_LUONG 
	FROM SAN_PHAM sp, SP_CN spcn
	WHERE sp.ID_SP=spcn.ID_SP and spcn.ID_CN= @ID_CN 
GO

CREATE PROC XEM_SAN_PHAM_HET @ID_CN INT
AS
	SELECT sp.TEN_SP
	FROM SAN_PHAM sp, SP_CN spcn
	WHERE sp.ID_SP=spcn.ID_SP and spcn.ID_CN= @ID_CN and spcn.SO_LUONG=0
GO