
CREATE PROC THEM_DANH_MUC_SP @TEN_LOAI NVARCHAR(50)
AS
	DECLARE @ID_LOAI INT
	SET @ID_LOAI = (SELECT MAX(ID_LOAI)+1
					FROM DANH_MUC_SP)
	insert into DANH_MUC_SP
	VALUES(@ID_LOAI, @TEN_LOAI)
GO

 
CREATE PROC SUA_DANH_MUC_SP @ID_LOAI INT, @TEN_LOAI NVARCHAR(50)
AS
	UPDATE DANH_MUC_SP
	SET TEN_LOAI = @TEN_LOAI
	WHERE ID_LOAI=@ID_LOAI
GO

CREATE PROC XOA_DANH_MUC_SP @ID_LOAI INT
AS
	DELETE DANH_MUC_SP
	WHERE ID_LOAI=@ID_LOAI
GO
 
CREATE PROC XEM_CHI_TIET_CHI_NHANH @ID_CN INT
AS
	SELECT TEN_CN, DIA_CHI_CN 
	FROM CHI_NHANH
	WHERE ID_CN=@ID_CN
GO


CREATE PROC XEM_SAN_PHAM_CON @ID_CN INT
AS
	SELECT sp.TEN_SP, spcn.SO_LUONG 
	FROM SAN_PHAM sp, SP_CN spcn
	WHERE sp.ID_SP=spcn.ID_SP and spcn.ID_CN= @ID_CN 
GO

CREATE PROC XEM_SAN_PHAM_HET @ID_CN INT
AS
	SELECT sp.TEN_SP
	FROM SAN_PHAM sp, SP_CN spcn
	WHERE sp.ID_SP=spcn.ID_SP and spcn.ID_CN= @ID_CN and spcn.SO_LUONG=0
GO

CREATE PROC TAO_DON_NHAP 
	@SAN_PHAM_NHAP INT,
	@CHI_NHANH_NHAP INT,
	@SO_LUONG_NHAP INT,
	@NHA_CUNG_CAP NVARCHAR(50)
AS
	--NẾU KHÔNG TỒN TẠI SẢN PHẨM ĐÓ THÌ SẼ RETURN
	IF(NOT EXISTS(SELECT *
				  FROM SP_CN
				  WHERE ID_SP=@SAN_PHAM_NHAP and ID_CN=@CHI_NHANH_NHAP))
		BEGIN
			RETURN;
		END
	--NẾU CÓ THÌ TA NHẬP ĐƠN HÀNG VÀ UPDATE SỐ LƯỢNG SẢN PHẨM HIỆN CÓ TẠI CỬA HÀNG
	ELSE
		BEGIN
			DECLARE @ID_DON_NHAP INT
			SET @ID_DON_NHAP = (SELECT MAX(ID_DON_NHAP)+1
							FROM DON_NHAP_HANG)
			INSERT INTO DON_NHAP_HANG
			VALUES (@ID_DON_NHAP, @SAN_PHAM_NHAP, @CHI_NHANH_NHAP, @SO_LUONG_NHAP, @NHA_CUNG_CAP, GETDATE())

			update SP_CN
			set SO_LUONG = SO_LUONG + @SO_LUONG_NHAP
			where ID_SP=@SAN_PHAM_NHAP and ID_CN=@CHI_NHANH_NHAP
		END
GO

CREATE PROC SP_DA_BAN_MOI_CN_THEO_QUY @QUY INT, @NAM INT, @CHI_NHANH INT --SẢN PHẨM ĐÃ BÁN THEO MỖI CHI NHÁNH THEO QUÝ
AS
	IF (@QUY = 1) --NẾU QUÝ 1 THÌ SẼ GOM NHỮNG ĐƠN HÀNG BÁN Ở THÁNG 1,2,3
		BEGIN
			SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
			FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
			WHERE SP.ID_SP=GH.ID_SP AND DH.CHI_NHANH=@CHI_NHANH AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
					AND (MONTH(DH.NGAY_BAN)=1 OR MONTH(DH.NGAY_BAN)=2 OR MONTH(DH.NGAY_BAN)=3)
			GROUP BY GH.ID_SP,  SP.TEN_SP
		END
	ELSE 
		BEGIN
			IF (@QUY = 2)  --NẾU QUÝ 2 THÌ SẼ GOM NHỮNG ĐƠN HÀNG BÁN Ở THÁNG 4,5,6
				BEGIN
					SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
					FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
					WHERE SP.ID_SP=GH.ID_SP AND DH.CHI_NHANH=@CHI_NHANH AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
							AND (MONTH(DH.NGAY_BAN)=4 OR MONTH(DH.NGAY_BAN)=5 OR MONTH(DH.NGAY_BAN)=6)
					GROUP BY GH.ID_SP, SP.TEN_SP
				END
			ELSE
				BEGIN
					IF (@QUY = 3)  --NẾU QUÝ 3 THÌ SẼ GOM NHỮNG ĐƠN HÀNG BÁN Ở THÁNG 7,8,9
						BEGIN
							SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
							FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
							WHERE SP.ID_SP=GH.ID_SP AND DH.CHI_NHANH=@CHI_NHANH AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
									AND (MONTH(DH.NGAY_BAN)=7 OR MONTH(DH.NGAY_BAN)=8 OR MONTH(DH.NGAY_BAN)=9)
							GROUP BY GH.ID_SP, SP.TEN_SP
						END
					ELSE
						BEGIN  --NẾU QUÝ 4 THÌ SẼ GOM NHỮNG ĐƠN HÀNG BÁN Ở THÁNG 10,11,12
							SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
							FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
							WHERE SP.ID_SP=GH.ID_SP AND DH.CHI_NHANH=@CHI_NHANH AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
									AND (MONTH(DH.NGAY_BAN)=10 OR MONTH(DH.NGAY_BAN)=11 OR MONTH(DH.NGAY_BAN)=12)
							GROUP BY GH.ID_SP, SP.TEN_SP
						END
				END
		END
	
GO

CREATE PROC TONG_SP_DA_BAN_THEO_QUY @QUY INT, @NAM INT --TỔNG CÁC SẢN PHẨM ĐÃ BÁN THEO QUÝ
AS
	IF (@QUY = 1) --NẾU QUÝ 1 THÌ SẼ GOM NHỮNG ĐƠN HÀNG BÁN Ở THÁNG 1,2,3
		BEGIN
			SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
			FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
			WHERE SP.ID_SP=GH.ID_SP AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
					AND (MONTH(DH.NGAY_BAN)=1 OR MONTH(DH.NGAY_BAN)=2 OR MONTH(DH.NGAY_BAN)=3)
			GROUP BY GH.ID_SP,  SP.TEN_SP
		END
	ELSE 
		BEGIN
			IF (@QUY = 2)  --NẾU QUÝ 2 THÌ SẼ GOM NHỮNG ĐƠN HÀNG BÁN Ở THÁNG 4,5,6
				BEGIN
					SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
					FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
					WHERE SP.ID_SP=GH.ID_SP AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
							AND (MONTH(DH.NGAY_BAN)=4 OR MONTH(DH.NGAY_BAN)=5 OR MONTH(DH.NGAY_BAN)=6)
					GROUP BY GH.ID_SP, SP.TEN_SP
				END
			ELSE
				BEGIN
					IF (@QUY = 3)  --NẾU QUÝ 3 THÌ SẼ GOM NHỮNG ĐƠN HÀNG BÁN Ở THÁNG 7,8,9
						BEGIN
							SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
							FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
							WHERE SP.ID_SP=GH.ID_SP AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
									AND (MONTH(DH.NGAY_BAN)=7 OR MONTH(DH.NGAY_BAN)=8 OR MONTH(DH.NGAY_BAN)=9)
							GROUP BY GH.ID_SP, SP.TEN_SP
						END
					ELSE
						BEGIN  --NẾU QUÝ 4 THÌ SẼ GOM NHỮNG ĐƠN HÀNG BÁN Ở THÁNG 10,11,12
							SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
							FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
							WHERE SP.ID_SP=GH.ID_SP AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
									AND (MONTH(DH.NGAY_BAN)=10 OR MONTH(DH.NGAY_BAN)=11 OR MONTH(DH.NGAY_BAN)=12)
							GROUP BY GH.ID_SP, SP.TEN_SP
						END
				END
		END
	
GO


CREATE PROC SP_DA_BAN_MOI_CN_THEO_THANG @THANG INT, @NAM INT, @CHI_NHANH INT --THỐNG KÊ SẢN PHẨM ĐÃ BÁN THEO THÁNG MỖI CHI NHÁNH
AS
	SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
	FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
	WHERE SP.ID_SP=GH.ID_SP AND DH.CHI_NHANH=@CHI_NHANH AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
			AND MONTH(DH.NGAY_BAN)=@THANG
	GROUP BY GH.ID_SP,  SP.TEN_SP
GO

CREATE PROC TONG_SP_DA_BAN_THEO_THANG @THANG INT, @NAM INT --THỐNG KÊ SẢN PHẨM ĐÃ BÁN THEO THÁNG TẤT CẢ CHI NHÁNH
AS
	SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
	FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
	WHERE SP.ID_SP=GH.ID_SP AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
			AND MONTH(DH.NGAY_BAN)=@THANG
	GROUP BY GH.ID_SP,  SP.TEN_SP
GO

CREATE PROC SP_DA_BAN_MOI_CN_THEO_NAM @NAM INT, @CHI_NHANH INT -- THỐNG KÊ SẢN PHẨM ĐÃ BÁN THEO NĂM MỖI CHI NHÁNH
AS
	SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
	FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
	WHERE SP.ID_SP=GH.ID_SP AND DH.CHI_NHANH=@CHI_NHANH AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
	GROUP BY GH.ID_SP,  SP.TEN_SP
GO

CREATE PROC TONG_SP_DA_BAN_THEO_NAM @NAM INT -- THỐNG KÊ SẢN PHẨM ĐÃ BÁN THEO NĂM TẤT CẢ CHI NHÁNH
AS
	SELECT GH.ID_SP, SP.TEN_SP, SUM(SO_LUONG)
	FROM GIO_HANG GH, DON_HANG DH, SAN_PHAM SP
	WHERE SP.ID_SP=GH.ID_SP AND GH.ID_DH=DH.ID_DH AND YEAR(DH.NGAY_BAN)=@NAM 
	GROUP BY GH.ID_SP,  SP.TEN_SP
GO

CREATE PROC TIM_KIEM @SEARCH NVARCHAR(50)
AS
	SELECT *
	FROM SAN_PHAM 
	WHERE TEN_SP Like '%'+@SEARCH+'%'
GO

